In [1]:
Pkg.add("DataFrames")
Pkg.update() # the output on your computer is bound to be much different (and the whole thing much faster!)

INFO: Nothing to be done
INFO: Updating METADATA...
INFO: Updating GeneratedTypes...
INFO: Updating GeneratedTables...
INFO: Updating TSne...
INFO: Updating GraphPlot...
INFO: Updating ComputeFramework...
INFO: Updating ELM...
INFO: Updating PlotlyJS...
INFO: Updating ROC...
INFO: Computing changes...
INFO: No packages to install, update or remove


In [3]:
using DataFrames

INFO: Recompiling stale cache file C:\Users\Zacharias\.julia\lib\v0.4\DataFrames.ji for module DataFrames.
INFO: Recompiling stale cache file C:\Users\Zacharias\.julia\lib\v0.4\StatsBase.ji for module StatsBase.
INFO: Recompiling stale cache file C:\Users\Zacharias\.julia\lib\v0.4\StatsFuns.ji for module StatsFuns.
INFO: Recompiling stale cache file C:\Users\Zacharias\.julia\lib\v0.4\DataArrays.ji for module DataArrays.
INFO: Recompiling stale cache file C:\Users\Zacharias\.julia\lib\v0.4\GZip.ji for module GZip.
INFO: Recompiling stale cache file C:\Users\Zacharias\.julia\lib\v0.4\SortingAlgorithms.ji for module SortingAlgorithms.
INFO: Recompiling stale cache file C:\Users\Zacharias\.julia\lib\v0.4\Docile.ji for module Docile.


In [4]:
df = DataFrame()

0×0 DataFrames.DataFrame

In [5]:
da = DataArray([1,2,3,4,5,6,7,8,9,10])

10-element DataArrays.DataArray{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [6]:
da1 = da
da2 = 2*da

10-element DataArrays.DataArray{Int64,1}:
  2
  4
  6
  8
 10
 12
 14
 16
 18
 20

In [7]:
df[:var1] = da1
df[:var2] = da2

10-element DataArrays.DataArray{Int64,1}:
  2
  4
  6
  8
 10
 12
 14
 16
 18
 20

In [8]:
names(df)

2-element Array{Symbol,1}:
 :var1
 :var2

In [9]:
rename!(df, [:var1, :var2], [:length, :width])

10×2 DataFrames.DataFrame
│ Row │ length │ width │
├─────┼────────┼───────┤
│ 1   │ 1      │ 2     │
│ 2   │ 2      │ 4     │
│ 3   │ 3      │ 6     │
│ 4   │ 4      │ 8     │
│ 5   │ 5      │ 10    │
│ 6   │ 6      │ 12    │
│ 7   │ 7      │ 14    │
│ 8   │ 8      │ 16    │
│ 9   │ 9      │ 18    │
│ 10  │ 10     │ 20    │

In [10]:
rename!(df, :width, :height)

10×2 DataFrames.DataFrame
│ Row │ length │ height │
├─────┼────────┼────────┤
│ 1   │ 1      │ 2      │
│ 2   │ 2      │ 4      │
│ 3   │ 3      │ 6      │
│ 4   │ 4      │ 8      │
│ 5   │ 5      │ 10     │
│ 6   │ 6      │ 12     │
│ 7   │ 7      │ 14     │
│ 8   │ 8      │ 16     │
│ 9   │ 9      │ 18     │
│ 10  │ 10     │ 20     │

In [11]:
df[:length]

10-element DataArrays.DataArray{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [12]:
var_name = "height"
df[symbol(var_name)]

10-element DataArrays.DataArray{Int64,1}:
  2
  4
  6
  8
 10
 12
 14
 16
 18
 20

In [13]:
showcols(df)

10×2 DataFrames.DataFrame
│ Col # │ Name   │ Eltype │ Missing │
├───────┼────────┼────────┼─────────┤
│ 1     │ length │ Int64  │ 0       │
│ 2     │ height │ Int64  │ 0       │

In [14]:
head(df)

6×2 DataFrames.DataFrame
│ Row │ length │ height │
├─────┼────────┼────────┤
│ 1   │ 1      │ 2      │
│ 2   │ 2      │ 4      │
│ 3   │ 3      │ 6      │
│ 4   │ 4      │ 8      │
│ 5   │ 5      │ 10     │
│ 6   │ 6      │ 12     │

In [15]:
tail(df)

6×2 DataFrames.DataFrame
│ Row │ length │ height │
├─────┼────────┼────────┤
│ 1   │ 5      │ 10     │
│ 2   │ 6      │ 12     │
│ 3   │ 7      │ 14     │
│ 4   │ 8      │ 16     │
│ 5   │ 9      │ 18     │
│ 6   │ 10     │ 20     │

In [16]:
describe(df)

length
Min      1.0
1st Qu.  3.25
Median   5.5
Mean     5.5
3rd Qu.  7.75
Max      10.0
NAs      0
NA%      0.0%

height
Min      2.0
1st Qu.  6.5
Median   11.0
Mean     11.0
3rd Qu.  15.5
Max      20.0
NAs      0
NA%      0.0%



In [17]:
df[1:5, [:length]]

5×1 DataFrames.DataFrame
│ Row │ length │
├─────┼────────┤
│ 1   │ 1      │
│ 2   │ 2      │
│ 3   │ 3      │
│ 4   │ 4      │
│ 5   │ 5      │

In [18]:
df[df[:length] .> 2, :]

8×2 DataFrames.DataFrame
│ Row │ length │ height │
├─────┼────────┼────────┤
│ 1   │ 3      │ 6      │
│ 2   │ 4      │ 8      │
│ 3   │ 5      │ 10     │
│ 4   │ 6      │ 12     │
│ 5   │ 7      │ 14     │
│ 6   │ 8      │ 16     │
│ 7   │ 9      │ 18     │
│ 8   │ 10     │ 20     │

In [19]:
ind = df[:length] .> 2
df[ind, :]

8×2 DataFrames.DataFrame
│ Row │ length │ height │
├─────┼────────┼────────┤
│ 1   │ 3      │ 6      │
│ 2   │ 4      │ 8      │
│ 3   │ 5      │ 10     │
│ 4   │ 6      │ 12     │
│ 5   │ 7      │ 14     │
│ 6   │ 8      │ 16     │
│ 7   │ 9      │ 18     │
│ 8   │ 10     │ 20     │

In [20]:
colwise(maximum, df)

2-element Array{Any,1}:
 [10]
 [20]

In [21]:
colwise(mean, df[[:length, :height]])

2-element Array{Any,1}:
 [5.5] 
 [11.0]

In [22]:
df[:weight] = DataArray([10,20,-1,15,25,5,10,20,-1,5])
df[df[:weight] .== -1,:weight] = NA # unknown cases relabeled as NA
mean(df[:weight])

NA

In [23]:
isna(df[:weight])

10-element BitArray{1}:
 false
 false
  true
 false
 false
 false
 false
 false
  true
 false

In [24]:
find(isna(df[:weight]))

2-element Array{Int64,1}:
 3
 9

In [25]:
m = round(Int64,mean(df[!isna(df[:weight]), :weight]))

14

In [26]:
df[isna(df[:weight]), :weight] = m
show(df[:weight])

[10,20,14,15,25,5,10,20,14,5]

In [27]:
delete!(df, :length)

10×2 DataFrames.DataFrame
│ Row │ height │ weight │
├─────┼────────┼────────┤
│ 1   │ 2      │ 10     │
│ 2   │ 4      │ 20     │
│ 3   │ 6      │ 14     │
│ 4   │ 8      │ 15     │
│ 5   │ 10     │ 25     │
│ 6   │ 12     │ 5      │
│ 7   │ 14     │ 10     │
│ 8   │ 16     │ 20     │
│ 9   │ 18     │ 14     │
│ 10  │ 20     │ 5      │

In [28]:
push!(df, @data([6, 15]))

In [29]:
deleterows!(df, 9:11)

8×2 DataFrames.DataFrame
│ Row │ height │ weight │
├─────┼────────┼────────┤
│ 1   │ 2      │ 10     │
│ 2   │ 4      │ 20     │
│ 3   │ 6      │ 14     │
│ 4   │ 8      │ 15     │
│ 5   │ 10     │ 25     │
│ 6   │ 12     │ 5      │
│ 7   │ 14     │ 10     │
│ 8   │ 16     │ 20     │

In [30]:
deleterows!(df, [1, 2, 4])

5×2 DataFrames.DataFrame
│ Row │ height │ weight │
├─────┼────────┼────────┤
│ 1   │ 6      │ 14     │
│ 2   │ 10     │ 25     │
│ 3   │ 12     │ 5      │
│ 4   │ 14     │ 10     │
│ 5   │ 16     │ 20     │

In [31]:
by(df, :weight, nrow)

5×2 DataFrames.DataFrame
│ Row │ weight │ x1 │
├─────┼────────┼────┤
│ 1   │ 5      │ 1  │
│ 2   │ 10     │ 1  │
│ 3   │ 14     │ 1  │
│ 4   │ 20     │ 1  │
│ 5   │ 25     │ 1  │

In [32]:
sort!(df, cols = [order(:height), order(:weight)])

5×2 DataFrames.DataFrame
│ Row │ height │ weight │
├─────┼────────┼────────┤
│ 1   │ 6      │ 14     │
│ 2   │ 10     │ 25     │
│ 3   │ 12     │ 5      │
│ 4   │ 14     │ 10     │
│ 5   │ 16     │ 20     │

In [37]:
Pkg.add("JSON")

INFO: Cloning cache of MNIST from git://github.com/johnmyleswhite/MNIST.jl.git
INFO: Installing MNIST v0.0.2
INFO: Package database updated


In [38]:
import JSON # "using JSON" would also work, but it's best to avoid that option

In [39]:
f = open("file.json")
X = JSON.parse(f)
close(f)

In [40]:
f = open("test.json", "w")
JSON.print(f, X)
close(f)

In [42]:
df = readtable("d:\\data\\CaffeineForTheForce.csv")

100×8 DataFrames.DataFrame
│ Row │ ID  │ MoviesWatched │ FavoriteEpisode │ Age   │ Gender │ BlogRole     │
├─────┼─────┼───────────────┼─────────────────┼───────┼────────┼──────────────┤
│ 1   │ 1   │ "-"           │ "VI"            │ "-"   │ "M"    │ "ActiveUser" │
│ 2   │ 2   │ "3"           │ "VI"            │ "45"  │ "-"    │ "NormalUser" │
│ 3   │ 3   │ "44"          │ "IV"            │ "33"  │ "F"    │ "-"          │
│ 4   │ 4   │ "3"           │ "-"             │ "40"  │ "M"    │ "Moderator"  │
│ 5   │ 5   │ "7"           │ "VI"            │ "25"  │ "F"    │ "NormalUser" │
│ 6   │ 6   │ "7"           │ "IV"            │ "29"  │ "M"    │ "ActiveUser" │
│ 7   │ 7   │ "4"           │ "VI"            │ "37"  │ "M"    │ "Moderator"  │
│ 8   │ 8   │ "6"           │ "III"           │ "20"  │ "M"    │ "ActiveUser" │
│ 9   │ 9   │ "7"           │ "IV"            │ "27"  │ "M"    │ "ActiveUser" │
│ 10  │ 10  │ "7"           │ "IV"            │ "30"  │ "F"    │ "NormalUser" │
│ 11  │ 11  │ "5"           │ "-"             │ "33"  │ "M"    │ "NormalUser" │
⋮
│ 89  │ 89  │ "7"           │ "VII"           │ "40"  │ "M"    │ "ActiveUser" │
│ 90  │ 90  │ "4"           │ "VI"            │ "145" │ "M"    │ "ActiveUser" │
│ 91  │ 91  │ "6"           │ "IV"            │ "19"  │ "F"    │ "NormalUser" │
│ 92  │ 92  │ "4"           │ "VI"            │ "29"  │ "M"    │ "NormalUser" │
│ 93  │ 93  │ "7"           │ "VI"            │ "30"  │ "M"    │ "NormalUser" │
│ 94  │ 94  │ "7"           │ "-"             │ "46"  │ "-"    │ "NormalUser" │
│ 95  │ 95  │ "5"           │ "V"             │ "50"  │ "M"    │ "NormalUser" │
│ 96  │ 96  │ "3"           │ "V"             │ "-"   │ "M"    │ "NormalUser" │
│ 97  │ 97  │ "4"           │ "IV"            │ "52"  │ "M"    │ "-"          │
│ 98  │ 98  │ "3"           │ "VI"            │ "49"  │ "M"    │ "ActiveUser" │
│ 99  │ 99  │ "6"           │ "III"           │ "12"  │ "M"    │ "ActiveUser" │
│ 100 │ 100 │ "-"           │ "IV"            │ "39"  │ "M"    │ "ActiveUser" │

│ Row │ MoneySpent │ FavoriteProduct │
├─────┼────────────┼─────────────────┤
│ 1   │ 1050       │ "VideoGame"     │
│ 2   │ 1000       │ "Book"          │
│ 3   │ 650        │ "Book"          │
│ 4   │ 11000      │ "Book"          │
│ 5   │ 100        │ "App"           │
│ 6   │ 250        │ "VideoGame"     │
│ 7   │ 700        │ "Book"          │
│ 8   │ 350        │ "VideoGame"     │
│ 9   │ 450        │ "App"           │
│ 10  │ 350        │ "Book"          │
│ 11  │ 50         │ "None"          │
⋮
│ 89  │ 350        │ "None"          │
│ 90  │ 250        │ "Book"          │
│ 91  │ 250        │ "App"           │
│ 92  │ 250        │ "VideoGame"     │
│ 93  │ 200        │ "App"           │
│ 94  │ 100        │ "Book"          │
│ 95  │ 50         │ "Book"          │
│ 96  │ 150        │ "None"          │
│ 97  │ 100        │ "Book"          │
│ 98  │ 750        │ "Book"          │
│ 99  │ 150        │ "VideoGame"     │
│ 100 │ 400        │ "Book"          │

In [43]:
df = readtable("d:\\data\\CaffeineForTheForce.csv", nastrings = ["N/A", "-", ""])

100×8 DataFrames.DataFrame
│ Row │ ID  │ MoviesWatched │ FavoriteEpisode │ Age │ Gender │ BlogRole     │
├─────┼─────┼───────────────┼─────────────────┼─────┼────────┼──────────────┤
│ 1   │ 1   │ NA            │ "VI"            │ NA  │ "M"    │ "ActiveUser" │
│ 2   │ 2   │ 3             │ "VI"            │ 45  │ NA     │ "NormalUser" │
│ 3   │ 3   │ 44            │ "IV"            │ 33  │ "F"    │ NA           │
│ 4   │ 4   │ 3             │ NA              │ 40  │ "M"    │ "Moderator"  │
│ 5   │ 5   │ 7             │ "VI"            │ 25  │ "F"    │ "NormalUser" │
│ 6   │ 6   │ 7             │ "IV"            │ 29  │ "M"    │ "ActiveUser" │
│ 7   │ 7   │ 4             │ "VI"            │ 37  │ "M"    │ "Moderator"  │
│ 8   │ 8   │ 6             │ "III"           │ 20  │ "M"    │ "ActiveUser" │
│ 9   │ 9   │ 7             │ "IV"            │ 27  │ "M"    │ "ActiveUser" │
│ 10  │ 10  │ 7             │ "IV"            │ 30  │ "F"    │ "NormalUser" │
│ 11  │ 11  │ 5             │ NA              │ 33  │ "M"    │ "NormalUser" │
⋮
│ 89  │ 89  │ 7             │ "VII"           │ 40  │ "M"    │ "ActiveUser" │
│ 90  │ 90  │ 4             │ "VI"            │ 145 │ "M"    │ "ActiveUser" │
│ 91  │ 91  │ 6             │ "IV"            │ 19  │ "F"    │ "NormalUser" │
│ 92  │ 92  │ 4             │ "VI"            │ 29  │ "M"    │ "NormalUser" │
│ 93  │ 93  │ 7             │ "VI"            │ 30  │ "M"    │ "NormalUser" │
│ 94  │ 94  │ 7             │ NA              │ 46  │ NA     │ "NormalUser" │
│ 95  │ 95  │ 5             │ "V"             │ 50  │ "M"    │ "NormalUser" │
│ 96  │ 96  │ 3             │ "V"             │ NA  │ "M"    │ "NormalUser" │
│ 97  │ 97  │ 4             │ "IV"            │ 52  │ "M"    │ NA           │
│ 98  │ 98  │ 3             │ "VI"            │ 49  │ "M"    │ "ActiveUser" │
│ 99  │ 99  │ 6             │ "III"           │ 12  │ "M"    │ "ActiveUser" │
│ 100 │ 100 │ NA            │ "IV"            │ 39  │ "M"    │ "ActiveUser" │

│ Row │ MoneySpent │ FavoriteProduct │
├─────┼────────────┼─────────────────┤
│ 1   │ 1050       │ "VideoGame"     │
│ 2   │ 1000       │ "Book"          │
│ 3   │ 650        │ "Book"          │
│ 4   │ 11000      │ "Book"          │
│ 5   │ 100        │ "App"           │
│ 6   │ 250        │ "VideoGame"     │
│ 7   │ 700        │ "Book"          │
│ 8   │ 350        │ "VideoGame"     │
│ 9   │ 450        │ "App"           │
│ 10  │ 350        │ "Book"          │
│ 11  │ 50         │ "None"          │
⋮
│ 89  │ 350        │ "None"          │
│ 90  │ 250        │ "Book"          │
│ 91  │ 250        │ "App"           │
│ 92  │ 250        │ "VideoGame"     │
│ 93  │ 200        │ "App"           │
│ 94  │ 100        │ "Book"          │
│ 95  │ 50         │ "Book"          │
│ 96  │ 150        │ "None"          │
│ 97  │ 100        │ "Book"          │
│ 98  │ 750        │ "Book"          │
│ 99  │ 150        │ "VideoGame"     │
│ 100 │ 400        │ "Book"          │

In [44]:
writetable("dataset.csv", df)

In [45]:
writetable("dataset.tsv", df)

In [46]:
S = "Mr. Smith is particularly fond of product #2235; what a surprise!"

"Mr. Smith is particularly fond of product #2235; what a surprise!"

In [47]:
Z = ""

for c in S
    if lowercase(c) in "qwertyuiopasdfghjklzxcvbnm "; Z = string(Z,c); end
end

In [48]:
println(Z)

Mr Smith is particularly fond of product  what a surprise


In [49]:
x = [1.0, 5.0, 3.0, 78.0, -2.0, -54.0]

6-element Array{Float64,1}:
   1.0
   5.0
   3.0
  78.0
  -2.0
 -54.0

In [50]:
x = convert(Array{Int8}, x)
show(x)

Int8[1,5,3,78,-2,-54]

In [51]:
x = convert(Array{Float16}, x)

6-element Array{Float16,1}:
   1.0
   5.0
   3.0
  78.0
  -2.0
 -54.0

In [52]:
'c' == "c"

false

In [53]:
age_new = ["young", "young", "mature", "middle-aged", "mature"]
is_young = (age_new .== "young")
is_middle_aged = (age_new .== "middle-aged")
is_mature = (age_new .== "mature")
show(is_young)

Bool[true,true,false,false,false]

In [54]:
age_new = ["young", "young", "", "mature", "middle-aged", "", "NA", "mature", ""]
is_missing = (age_new .== "") | (age_new .== "NA")
show(is_missing)

Bool[false,false,true,false,false,true,true,false,true]

In [55]:
NA_denotations = ["", "NA", "na", "N/A", "-"]

5-element Array{ASCIIString,1}:
 ""   
 "NA" 
 "na" 
 "N/A"
 "-"  

In [56]:
is_missing = [age_value in NA_denotations for age_value in age_new]

9-element Array{Any,1}:
 false
 false
  true
 false
 false
  true
  true
 false
  true

In [57]:
S_new = lowercase(S)

"mr. smith is particularly fond of product #2235; what a surprise!"

In [58]:
X = ["Julia is a relatively new programming language", "Julia can be used in data science", "Data science is used to derive insights from data", "Data is often noisy"]

4-element Array{ASCIIString,1}:
 "Julia is a relatively new programming language"   
 "Julia can be used in data science"                
 "Data science is used to derive insights from data"
 "Data is often noisy"                              

In [59]:
temp = [split(lowercase(x), " ") for x in X]
vocabulary = unique(temp[1])
for T in temp[2:end]
    vocabulary = union(vocabulary, T)
end
vocabulary = sort(vocabulary)
N = length(vocabulary)
show(vocabulary)

SubString{ASCIIString}["a","be","can","data","derive","from","in","insights","is","julia","language","new","noisy","often","programming","relatively","science","to","used"]

In [60]:
n = length(X)
VX = zeros(Int8, n, N) # Vectorized X
for i = 1:n
    temp = split(lowercase(X[i]))
    for T in temp
        ind = find(T .== vocabulary)
        VX[i,ind] = 1
    end    
end
println(VX)

Int8[1 0 0 0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 0
     0 1 1 1 0 0 1 0 0 1 0 0 0 0 0 0 1 0 1
     0 0 0 1 1 1 0 1 1 0 0 0 0 0 0 0 1 1 1
     0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0]
